name: Teleporter
version: @version@
main: at.coderdojo.teleporter.Teleporter
load: STARTUP
authors: [Minecraft, Mastercoders]
description: Beispielplugin zum Teleportieren
website: https://coderdojo-linz.github.io/
commands:
  sayhello:
    description: Says hello
    usage: /sayhello
  teleportziel:
    description: Ziel, an das wir uns teleportieren wollen.
    usage: /teleportziel
  teleportzu:
    description: Teleportiere zum vorher markierten Ziel.
    usage: /teleportzu

